In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [3]:
### Scrape All ID

```url = 'https://www.oktatas.hu/kozneveles/intezmenykereso/intezmenyek_a_szamok_tukreben/erettsegi_statisztikak/!DARI_ErettsegiStat/oh.php?id=kir_erett_talalat&oldal='
head = {'Cookie' : 'wcmid=user#21976512; DARI_ErettsegiStat-sessionid=uj5a81vqh5ll064p9tncv32tl2; Mainappstate-DARI_ErettsegiStat=%2Foh.php; DARI_Intezmenykereso-sessionid=c4vvvhg6g9vivaupgir6b0f695; Mainappstate-DARI_Intezmenykereso=%2Foh.php; Mainappstate-KIR_Intezmenykereso=%2FIntezmeny%2FIndex%2F035218'}
OMs = []
pages = 23
for i in range(pages):
    res = requests.get(url + str(i+1), headers=head)
    soup = BeautifulSoup(res.content)
    OMs.extend([tr.find_all('td')[1].text for tr in soup.find_all('tr')[2:-1]])
    print(f'The {i+1}. page Done!')```

In [33]:
df = pd.read_csv('./SchoolData/omid_to_collect.csv')

In [34]:
df = df['0'].drop_duplicates(keep='first')

omid

In [35]:
df_All = pd.DataFrame(columns=['omid', 'sub_school_len', 'erettsegi_table_len', 'admin', 'sub_schools', 'basic', 'students', 'teachers', 'iq_2019', 'erettsegi_2020', 'enroll_2020'])

for omid in df:
    omid = format(omid, '06d')
    res = requests.get('https://www.oktatas.hu/kozneveles/intezmenykereso/koznevelesi_intezmenykereso/!DARI_Intezmenykereso/oh.php?id=kir_int_mod&int_omkod=' + omid)
    soup = BeautifulSoup(res.content)
    #Fotablazat
    html_admin = str(soup.findAll('table')[2])
    #df_admin = pd.read_html(html_admin, index_col=1)[0].drop(columns=0).rename(columns={2 : 'value'})

    #### Feladatellatasi hely

    html_sub_schools = soup.select('#adat_felhely table')[1::2]

    #len(html_sub_schools)

    #df_subs = pd.concat(pd.read_html(str(html_sub_schools))).drop(columns=5).rename(columns={0:'sub_id',1 : 'sub_school', 2 : 'school_address', 3 : 'school_country', 4 : 'school_type'}).reset_index(drop=True)



    #### Basic Stats on Children
    html_basics = str(soup.select('#adata01t01 table'))
    html_teachers = str(soup.select('#adata01t06 table'))
    html_students = str(soup.select('#adata04t18 table'))

    #df_basics = pd.read_html(html_basics,header=[0,1,2], index_col=0)[0]

    # Students
    #df_teachers = pd.read_html(html_teachers, index_col=[1,2])[0].drop(columns=[0,4]).rename(columns={3 : 'count'})

    #df_student = pd.read_html(html_students, index_col=0, header=[0,1,2])[0]

    ### Competency Test - get the average of all recent results
    html_iq = str(soup.select('#adat_okm2019 table'))

    #df_iq  = pd.read_html(html_iq, header=1)[0].drop(columns='Unnamed: 0')

    #Get only One feladat ellatasi hely
    #df_iq[df_iq['Telephely megnevezése és címe'].str.contains(school_address)]



    ### Enrollment data 2020 - need more? maybe
    html_enroll2020 = str(soup.select('#adat_kifir2020 table'))

    #df_enroll2020 = pd.read_html(html_enroll2020, header=0)[0].drop(columns='Unnamed: 0')

    #Erettsegi

    html_2020 = soup.select('#adat_stat2020_vtargy table')[0::2]

    #len(html_2020) ### give you all table

    ## by concat we create one unified table 

    #df_erett2020 = pd.concat(pd.read_html(str(html_2020), header=0)).drop(columns='Unnamed: 0').rename(columns={'Unnamed: 1' : 'Telephely megnevezése és címe'})

    df_collection = {
        'omid' : omid,
        'sub_school_len' : len(html_sub_schools),
        'erettsegi_table_len' : len(html_2020),
        'admin' : html_admin,
        'sub_schools' : html_sub_schools,
        'basic' : html_basics,
        'students' : html_students,
        'teachers' : html_teachers,
        'iq_2019' : html_iq,
        'erettsegi_2020' : html_2020,
        'enroll_2020' : html_enroll2020

    }

    df_omid = pd.DataFrame.from_dict(df_collection, orient='index').T
    df_All = pd.concat([df_All, df_omid])
    print(omid + ' - Done')
    

df_All.to_csv('./SchoolData/raw_school_data.csv.gz', encoding='utf-8-sig')

027240 - Done
027264 - Done
027396 - Done
027397 - Done
027398 - Done
027399 - Done
027401 - Done
027402 - Done
027406 - Done
027407 - Done
027413 - Done
027415 - Done
027417 - Done
027425 - Done
027437 - Done
027743 - Done
027816 - Done
027873 - Done
027938 - Done
027939 - Done
027940 - Done
027942 - Done
027943 - Done
027944 - Done
027945 - Done
027946 - Done
027948 - Done
027949 - Done
027951 - Done
027953 - Done
027955 - Done
027956 - Done
027959 - Done
027975 - Done
027977 - Done
027986 - Done
028279 - Done
028280 - Done
028300 - Done
028374 - Done
028375 - Done
028376 - Done
028380 - Done
028382 - Done
028387 - Done
028388 - Done
028393 - Done
028395 - Done
028396 - Done
028409 - Done
028430 - Done
028456 - Done
028992 - Done
028993 - Done
029261 - Done
029262 - Done
029263 - Done
029264 - Done
029265 - Done
029280 - Done
029281 - Done
029306 - Done
029308 - Done
029324 - Done
029340 - Done
029379 - Done
029382 - Done
029736 - Done
029737 - Done
029741 - Done
029742 - Done
029743 - Done
029744 - Done
029745 - Done
029747 - Done
029752 - Done
029799 - Done
030046 - Done
030066 - Done
030081 - Done
030175 - Done
030179 - Done
030180 - Done
030181 - Done
030182 - Done
030183 - Done
030186 - Done
030192 - Done
030194 - Done
030228 - Done
030232 - Done
030491 - Done
030502 - Done
030531 - Done
030546 - Done
030549 - Done
030693 - Done
030694 - Done
030695 - Done
030696 - Done
030697 - Done
030698 - Done
030701 - Done
030705 - Done
030711 - Done
030712 - Done
030724 - Done
030725 - Done
030728 - Done
030741 - Done
031107 - Done
031197 - Done
031198 - Done
031199 - Done
031200 - Done
031201 - Done
031202 - Done
031203 - Done
031204 - Done
031205 - Done
031208 - Done
031231 - Done
031235 - Done
031238 - Done
031597 - Done
031598 - Done
031599 - Done
031603 - Done
031607 - Done
031610 - Done
031617 - Done
031619 - Done
031631 - Done
031838 - Done
031862 - Done
031931 - Done
031932 - Done
031934 - Done
031936 - Done
031937 - Done
031945 - Done
031960 - Done
031966 - Done
031973 - Done
031986 - Done
032284 - Done
032285 - Done
032286 - Done
032289 - Done
032292 - Done
032295 - Done
032305 - Done
032353 - Done
032378 - Done
032450 - Done
032460 - Done
032464 - Done
032548 - Done
032549 - Done
032550 - Done
032551 - Done
032552 - Done
032554 - Done
032555 - Done
032557 - Done
032560 - Done
032561 - Done
032562 - Done
032563 - Done
032564 - Done
032568 - Done
032569 - Done
032571 - Done
032575 - Done
032579 - Done
032580 - Done
032582 - Done
032583 - Done
032585 - Done
032597 - Done
032600 - Done
032614 - Done
032616 - Done
032618 - Done
032630 - Done
032635 - Done
032637 - Done
032655 - Done
032680 - Done
033128 - Done
033387 - Done
033431 - Done
033644 - Done
033645 - Done
033646 - Done
033647 - Done
033648 - Done
033649 - Done
033650 - Done
033651 - Done
033652 - Done
033653 - Done
033654 - Done
033657 - Done
033659 - Done
033660 - Done
033661 - Done
033665 - Done
033666 - Done
033667 - Done
033668 - Done
033685 - Done
033687 - Done
033699 - Done
033981 - Done
034141 - Done
034143 - Done
034145 - Done
034146 - Done
034148 - Done
034149 - Done
034155 - Done
034156 - Done
034168 - Done
034178 - Done
034796 - Done
034799 - Done
034802 - Done
034836 - Done
034851 - Done
034853 - Done
034863 - Done
034866 - Done
034877 - Done
034894 - Done
034905 - Done
034923 - Done
034949 - Done
034982 - Done
035072 - Done
035101 - Done
035115 - Done
035152 - Done
035187 - Done
035218 - Done
035219 - Done
035220 - Done
035222 - Done
035223 - Done
035225 - Done
035226 - Done
035227 - Done
035228 - Done
035229 - Done
035230 - Done
035231 - Done
035232 - Done
035233 - Done
035234 - Done
035235 - Done
035236 - Done
035237 - Done
035239 - Done
035242 - Done
035243 - Done
035244 - Done
035245 - Done
035246 - Done
035247 - Done
035248 - Done
035249 - Done
035250 - Done
035252 - Done
035253 - Done
035254 - Done
035255 - Done
035256 - Done
035257 - Done
035259 - Done
035260 - Done
035261 - Done
035265 - Done
035266 - Done
035269 - Done
035271 - Done
035273 - Done
035277 - Done
035278 - Done
035279 - Done
035281 - Done
035282 - Done
035283 - Done
035284 - Done
035288 - Done
035289 - Done
035301 - Done
035302 - Done
035304 - Done
035305 - Done
035307 - Done
035310 - Done
035312 - Done
035313 - Done
035314 - Done
035315 - Done
035316 - Done
035319 - Done
035321 - Done
035322 - Done
035323 - Done
035324 - Done
035326 - Done
035327 - Done
035328 - Done
035339 - Done
035343 - Done
035344 - Done
035346 - Done
035348 - Done
035349 - Done
035357 - Done
035358 - Done
035360 - Done
035362 - Done
035377 - Done
035384 - Done
035385 - Done
035408 - Done
035409 - Done
035445 - Done
035452 - Done
035454 - Done
035462 - Done
035464 - Done
035468 - Done
035483 - Done
035491 - Done
035506 - Done
035555 - Done
035562 - Done
035566 - Done
035606 - Done
035625 - Done
035843 - Done
035844 - Done
035890 - Done
035987 - Done
035990 - Done
035992 - Done
035994 - Done
036005 - Done
036007 - Done
036014 - Done
036032 - Done
036057 - Done
036263 - Done
036276 - Done
036360 - Done
036371 - Done
036378 - Done
036379 - Done
036384 - Done
036385 - Done
036391 - Done
036394 - Done
036396 - Done
036410 - Done
036416 - Done
036598 - Done
036626 - Done
036723 - Done
036724 - Done
036725 - Done
036728 - Done
036729 - Done
036732 - Done
036733 - Done
036734 - Done
036756 - Done
036757 - Done
037165 - Done
037166 - Done
037167 - Done
037169 - Done
037170 - Done
037171 - Done
037172 - Done
037178 - Done
037181 - Done
037185 - Done
037206 - Done
037224 - Done
037234 - Done
037320 - Done
037513 - Done
037526 - Done
037630 - Done
037631 - Done
037632 - Done
037634 - Done
037635 - Done
037636 - Done
037640 - Done
037641 - Done
037730 - Done
037742 - Done
037775 - Done
037802 - Done
037828 - Done
037857 - Done
037878 - Done
037882 - Done
037923 - Done
037935 - Done
038071 - Done
038090 - Done
038115 - Done
038127 - Done
038139 - Done
038156 - Done
038245 - Done
038281 - Done
038368 - Done
038425 - Done
039227 - Done
039378 - Done
039381 - Done
039554 - Done
039770 - Done
039907 - Done
040015 - Done
040234 - Done
040365 - Done
062576 - Done
063879 - Done
064329 - Done
064887 - Done
100510 - Done
100523 - Done
100527 - Done
100534 - Done
100537 - Done
100539 - Done
100563 - Done
100565 - Done
100566 - Done
100569 - Done
100573 - Done
100804 - Done
101138 - Done
101433 - Done
101488 - Done
101496 - Done
101497 - Done
101503 - Done
101508 - Done
101641 - Done
101669 - Done
101671 - Done
102290 - Done
102547 - Done
102635 - Done
102648 - Done
102677 - Done
102703 - Done
102731 - Done
102759 - Done
102783 - Done
102794 - Done
200002 - Done
200005 - Done
200031 - Done
200047 - Done
200052 - Done
200078 - Done
200185 - Done
200203 - Done
200232 - Done
200290 - Done
200300 - Done
200304 - Done
200324 - Done
200328 - Done
200329 - Done
200345 - Done
200346 - Done
200406 - Done
200407 - Done
200410 - Done
200415 - Done
200423 - Done
200435 - Done
200444 - Done
200446 - Done
200447 - Done
200475 - Done
200479 - Done
200483 - Done
200489 - Done
200509 - Done
200518 - Done
200584 - Done
200598 - Done
200599 - Done
200607 - Done
200627 - Done
200650 - Done
200659 - Done
200667 - Done
200669 - Done
200672 - Done
200679 - Done
200680 - Done
200696 - Done
200708 - Done
200777 - Done
200779 - Done
200783 - Done
200838 - Done
200842 - Done
200868 - Done
200886 - Done
200893 - Done
200908 - Done
200909 - Done
200917 - Done
200923 - Done
200928 - Done
200938 - Done
200958 - Done
200963 - Done
201021 - Done
201033 - Done
201035 - Done
201038 - Done
201173 - Done
201176 - Done
201188 - Done
201189 - Done
201190 - Done
201200 - Done
201202 - Done
201217 - Done
201225 - Done
201238 - Done
201251 - Done
201260 - Done
201279 - Done
201286 - Done
201326 - Done
201348 - Done
201354 - Done
201362 - Done
201400 - Done
201410 - Done
201418 - Done
201425 - Done
201474 - Done
201477 - Done
201491 - Done
201492 - Done
201505 - Done
201512 - Done
201521 - Done
201550 - Done
201560 - Done
201573 - Done
201575 - Done
201594 - Done
201600 - Done
201601 - Done
201622 - Done
201625 - Done
201640 - Done
201641 - Done
201656 - Done
201676 - Done
201690 - Done
201695 - Done
201698 - Done
201704 - Done
201724 - Done
201728 - Done
201731 - Done
201750 - Done
201756 - Done

201762 - Done
201791 - Done
201793 - Done
201799 - Done
202705 - Done
202718 - Done
202722 - Done
202723 - Done
202724 - Done
202725 - Done
202727 - Done
202728 - Done
202734 - Done
202735 - Done
202736 - Done
202737 - Done
202738 - Done
202739 - Done
202740 - Done
202741 - Done
202742 - Done
202743 - Done
202744 - Done
202745 - Done
202755 - Done
202785 - Done
202801 - Done
202828 - Done
202830 - Done
202924 - Done
202971 - Done
203027 - Done
203028 - Done
203029 - Done
203030 - Done
203031 - Done
203032 - Done
203033 - Done
203034 - Done
203035 - Done
203036 - Done
203037 - Done
203038 - Done
203039 - Done
203040 - Done
203041 - Done
203042 - Done
203043 - Done
203044 - Done
203045 - Done
203046 - Done
203047 - Done
203048 - Done
203049 - Done
203050 - Done
203051 - Done
203052 - Done
203053 - Done
203054 - Done
203055 - Done
203056 - Done
203058 - Done
203059 - Done
203060 - Done
203061 - Done
203062 - Done
203064 - Done
203065 - Done
203066 - Done
203067 - Done
203068 - Done
203069 - Done
203078 - Done
203102 - Done
203109 - Done
203112 - Done
203117 - Done
203167 - Done
203168 - Done
203175 - Done
203177 - Done
203195 - Done
203196 - Done
203204 - Done
203246 - Done
203259 - Done
203262 - Done
203265 - Done
203365 - Done
203367 - Done
203375 - Done
203378 - Done
203379 - Done
203384 - Done
203385 - Done
203391 - Done
203405 - Done
203408 - Done
203419 - Done
203420 - Done
203421 - Done
203424 - Done

In [71]:
#soup.find('div', id='adat_kifir2020').find('table')

In [83]:
df_All[df_All['erettsegi_table_len']==40]

,omid,sub_school_len,erettsegi_table_len,admin,sub_schools,basic,students,teachers,iq_2019,erettsegi_2020,enroll_2020
0,200345,35,40,"<table align=""center"" border=""0"" cellpadding=""...","[[\n, [\n, <td align=""center"" bgcolor=""#FFE79D...","[<table align=""center"" border=""0"" cellpadding=...","[<table align=""center"" border=""0"" cellpadding=...","[<table align=""center"" border=""0"" cellpadding=...",[],"[[\n, [\n, <td width=""40""> </td>, \n, <td widt...",[]

In [102]:
## Test on Szilagyi

In [56]:
omid = '035219'

In [57]:
res = requests.get('https://www.oktatas.hu/kozneveles/intezmenykereso/koznevelesi_intezmenykereso/!DARI_Intezmenykereso/oh.php?id=kir_int_mod&int_omkod=' + omid)

In [58]:
soup = BeautifulSoup(res.content)

In [59]:
#Fotablazat
html_admin = str(soup.findAll('table')[2])
df_admin = pd.read_html(html_admin, index_col=1)[0].drop(columns=0).rename(columns={2 : 'value'})

In [60]:
## Data gather from admin table: 

#school_id = df_admin.loc['Az intézmény OM azonosítója:'][2]
#school_name = df_admin.loc['Az intézmény megnevezése:'][2]
#school_dean = df_admin.loc['Az intézmény vezetője:'][2]
#school_dean_title = df_admin.loc['Beosztása:'].iloc[0][2]
#school_address = df_admin.loc['Címe:'][2]
#school_type = df_admin.loc['Ellátott feladatok:'][2].split(',')

In [61]:
#### Feladatellatasi hely

In [62]:
html_sub_schools = soup.find(id='adat_felhely').findAll('table')[1::2]

In [63]:
len(html_sub_schools)

1

In [26]:
df_subs = pd.concat(pd.read_html(str(html_sub_schools))).drop(columns=5).rename(columns={0:'sub_id',1 : 'sub_school', 2 : 'school_address', 3 : 'school_country', 4 : 'school_type'}).reset_index(drop=True)

In [27]:
df_subs

,sub_id,sub_school,school_address,school_country,school_type
0,1,"Miroslav Krleža Horvát Óvoda, Általános Iskola...","7624 Pécs, Szigeti út 97.",Baranya,általános iskolai nevelés-oktatás (alsó tagoza...
1,4,"Miroslav Krleža Horvát Óvoda, Általános Iskola...","7624 Pécs, Acsády Ignác utca 8",Baranya,óvodai nevelés

In [65]:
#### Basic Stats on Children
html_basics = str(soup.find('div', id='adata01t01').find('table'))
html_teachers = str(soup.find('div', id='adata01t06').find('table'))
html_students = str(soup.find('div', id='adata04t18').find('table'))

In [66]:
df_basics = pd.read_html(html_basics,header=[0,1,2], index_col=0)[0]

In [67]:
# teachers
df_teachers = pd.read_html(html_teachers, index_col=[1,2])[0].drop(columns=[0,4]).rename(columns={3 : 'count'})

In [68]:
# Students

df_student = pd.read_html(html_students, index_col=0, header=[0,1,2])[0]

In [69]:
### Competency Test - get the average of all recent results
html_iq = str(soup.find('div', id='adat_okm2019').find('table'))

In [70]:
df_iq  = pd.read_html(html_iq, header=1)[0].drop(columns='Unnamed: 0')

In [71]:
#Get only One feladat ellatasi hely
#df_iq[df_iq['Telephely megnevezése és címe'].str.contains(school_address)]

In [72]:
### Enrollment data 2020 - need more? maybe
html_enroll2020 = str(soup.find('div', id='adat_kifir2020').find('table'))

In [73]:
df_enroll2020 = pd.read_html(html_enroll2020, header=0)[0].drop(columns='Unnamed: 0')

In [74]:
#Erettsegi

html_2020 = soup.find('div', id='adat_stat2020_vtargy').findAll('table')[0::2]

In [75]:
len(html_2020) ### give you all table

1

In [76]:
## by concat we create one unified table 

df_erett2020 = pd.concat(pd.read_html(str(html_2020), header=0)).drop(columns='Unnamed: 0').rename(columns={'Unnamed: 1' : 'Telephely megnevezése és címe'})

In [82]:
df_collection = {
    'omid' : omid,
    'sub_school_len' : len(html_sub_schools),
    'erettsegi_table_len' : len(html_2020),
    'admin' : html_admin,
    'sub_schools' : html_sub_schools,
    'basic' : html_basics,
    'students' : html_students,
    'teachers' : html_teachers,
    'iq_2019' : html_iq,
    'erettsegi_2020' : html_2020,
    'enroll_2020' : html_enroll2020
    
}

In [83]:
pd.DataFrame(df_collection)

,omid,sub_school_len,erettsegi_table_len,admin,sub_schools,basic,students,teachers,iq_2019,erettsegi_2020,enroll_2020
0,035219,1,1,"<table align=""center"" border=""0"" cellpadding=""...","[\n, [\n, [001], \n, [<a class=""slide"" id=""001...","<table align=""center"" border=""0"" cellpadding=""...","<table align=""center"" border=""0"" cellpadding=""...","<table align=""center"" border=""0"" cellpadding=""...","<table align=""center"" border=""0"" cellpadding=""...","[\n, [\n, [ ], \n, [ ], \n, [érettségi vizsgat...","<table align=""center"" border=""0"" cellpadding=""..."

In [70]:
################################################################################

#### Basic Quantitative Data - Summerize for all subschools

In [45]:
#### Basic Stats on Children
t_basics = soup.find('div', id='adata01t01').find('table')
t_teachers = soup.find('div', id='adata01t06').find('table')
t_students = soup.find('div', id='adata04t18').find('table')

In [56]:

df_basics

          Összes feladatel-  látási helyek száma  \
          Összes feladatel-  látási helyek száma
          Összes feladatel-  látási helyek száma
Gimnázium                                      1
Összesen                                       1

          Gyermekek, tanulók nyitó létszáma          \
                                   Összesen   ebből
                                   Összesen leányok
Gimnázium                               501     256
Összesen                                501     256

                                                              \

          gyógypeda-gógiai nevelésben, oktatásban résztvevők
Gimnázium                                                  3
Összesen                                                   3

                                          \

          felnőttok-tatásban részt vevők
Gimnázium                              0
Összesen                               0

          Fő munkaviszony keretében pedagógus, oktató munkakörben alkalmazottak nyitóállománya  \
                                                                                      Összesen
                                                                                      Összesen
Gimnázium                                                 51
Összesen                                                  51

                    Osztályterem, szaktanterem / csoportszoba összesen  \
          ebből nők Osztályterem, szaktanterem / csoportszoba összesen
          ebből nők Osztályterem, szaktanterem / csoportszoba összesen
Gimnázium        36                                                 21
Összesen         36                                                 21

          Osztályok, csoportok száma összesen  \
          Osztályok, csoportok száma összesen
          Osztályok, csoportok száma összesen
Gimnázium                                  16
Összesen                                   16

          Nevelő és oktató munkát közvetlenül segítők, egyéb munkakörben dolgozók nyitóállománya  \
                                                                                        Összesen
                                                                                        Összesen
Gimnázium                                                 16
Összesen                                                  16


          Ebből nők
          Ebből nők
Gimnázium        10
Összesen         10

##### Basics

In [295]:
df_basics  = pd.read_html(str(t_basics),header=0, index_col=0)[0]

no_hs_student = df_basics['Gyermekek, tanulók nyitó létszáma'].loc['Gimnázium']  
no_hs_student_female = df_basics['Gyermekek, tanulók nyitó létszáma.1'].loc['Gimnázium']  
no_rooms = df_basics['Osztályterem, szaktanterem / csoportszoba összesen'].loc['Gimnázium']
no_classes= df_basics['Osztályok, csoportok száma összesen'].loc['Gimnázium']

##### Students

In [296]:
df_students = pd.read_html(str(t_students), index_col=[1,2])[0]

### tons of important info ignored here
no_fail = df_students.loc[('évfolyamismétlő','évfolyamismétlő')][3]

##### Teachers

In [297]:
df_teachers = pd.read_html(str(t_teachers), index_col=0, header=0)[0]
fulltime_teachers = df_teachers['Összesen'].loc['Teljes munkaidős']
parttime_teachers = df_teachers['Összesen'].loc['Részmunkaidős']
total_teachers = df_teachers['Összesen'].loc['Összesen']

### Competency test

In [298]:
### Competency Test - get the average of all recent results

t_iq = soup.find('div', id='adat_okm2019').find('table')
df_competency = pd.read_html(str(t_iq),index_col=3, header=1)[0]

math_competency = df_competency['Matematika'].mean()
lit_competency = df_competency['Szövegértés'].mean()

### Erettsegi test

In [299]:
### Erettsegi Tables - GSCI

t_2018= soup.find('div', id='adat_stat2018_vtargy').find('table')
t_2019= soup.find('div', id='adat_stat2019_vtargy').find('table')
t_2020= soup.find('div', id='adat_stat2020_vtargy').find('table')

In [300]:
df_erett_2020 = pd.read_html(str(t_2020), header=0)[0]

In [301]:
hu_gcse = df_erett_2020[(df_erett_2020['érettségi vizsgatárgy']=='magyar nyelv és irodalom') & (df_erett_2020['szint']=='közép')][['jelentkezők száma', 'százalékos átlag','osztályzat átlag']].values
hu_gcse_pop,hu_gcse_perc,hu_gcse_avg = hu_gcse[0] if len(hu_gcse)==1 else [None,None,None]

hu_A = df_erett_2020[(df_erett_2020['érettségi vizsgatárgy']=='magyar nyelv és irodalom') & (df_erett_2020['szint']=='emelt')][['jelentkezők száma', 'százalékos átlag','osztályzat átlag']].values
hu_A_pop,hu_A_perc,hu_A_avg = hu_A[0] if len(hu_A)==1 else [None,None,None]

math_gcse = df_erett_2020[(df_erett_2020['érettségi vizsgatárgy']=='matematika') & (df_erett_2020['szint']=='közép')][['jelentkezők száma', 'százalékos átlag','osztályzat átlag']].values
math_gcse_pop,math_gcse_perc,math_gcse_avg = math_gcse[0] if len(math_gcse)==1 else [None,None,None]

math_A = df_erett_2020[(df_erett_2020['érettségi vizsgatárgy']=='matematika') & (df_erett_2020['szint']=='emelt')][['jelentkezők száma', 'százalékos átlag','osztályzat átlag']].values
math_A_pop,math_A_perc,math_A_avg = math_A[0] if len(math_A)==1 else [None,None,None]

hist_gcse = df_erett_2020[(df_erett_2020['érettségi vizsgatárgy']=='történelem') & (df_erett_2020['szint']=='közép')][['jelentkezők száma', 'százalékos átlag','osztályzat átlag']].values
hist_gcse_pop,hist_gcse_perc,hist_gcse_avg = hist_gcse[0] if len(hist_gcse)==1 else [None,None,None]

hist_A = df_erett_2020[(df_erett_2020['érettségi vizsgatárgy']=='történelem') & (df_erett_2020['szint']=='emelt')][['jelentkezők száma', 'százalékos átlag','osztályzat átlag']].values
hist_A_pop,hist_A_perc,hist_A_avg = hist_A[0] if len(hist_A)==1 else [None,None,None]

eng_gcse = df_erett_2020[(df_erett_2020['érettségi vizsgatárgy']=='angol nyelv') & (df_erett_2020['szint']=='közép')][['jelentkezők száma', 'százalékos átlag','osztályzat átlag']].values
eng_gcse_pop,eng_gcse_perc,eng_gcse_avg = eng_gcse[0] if len(eng_gcse)==1 else [None,None,None]

eng_A= df_erett_2020[(df_erett_2020['érettségi vizsgatárgy']=='angol nyelv') & (df_erett_2020['szint']=='emelt')][['jelentkezők száma', 'százalékos átlag','osztályzat átlag']].values
eng_A_pop,eng_A_perc,eng_A_avg = eng_A[0] if len(eng_A)==1 else [None,None,None]

### Acceptence Rate

In [302]:
### Enrollment data
t_enroll2019 = soup.find('div', id='adat_kifir2019').find('table')

In [303]:
## Calcualte applied and accepted rates

enroll2019 = pd.read_html(str(t_enroll2019), header=0)[0]

first_place_acceptance_rate = enroll2019['1. helyen jelentkezettek közül a felvettek száma'].sum()/ enroll2019['Jelentkezők száma'].sum()
acceptance_rate = enroll2019['Felvettek száma'].sum() / enroll2019['Jelentkezők száma'].sum()

In [304]:
%who

BeautifulSoup	 acceptance_rate	 acceptence_rate	 address_id	 df_admin	 df_basics	 df_competency	 df_erett_2020	 df_students
df_teachers	 eng_A	 eng_A_avg	 eng_A_perc	 eng_A_pop	 eng_gcse	 eng_gcse_avg	 eng_gcse_perc	 eng_gcse_pop
enroll2019	 first_place_acceptance_rate	 first_place_acceptence_rate	 fulltime_teachers	 hist_A	 hist_A_avg	 hist_A_perc	 hist_A_pop	 hist_gcse
hist_gcse_avg	 hist_gcse_perc	 hist_gcse_pop	 hu_A	 hu_A_avg	 hu_A_perc	 hu_A_pop	 hu_gcse	 hu_gcse_avg
hu_gcse_perc	 hu_gcse_pop	 hu_gcse_res	 lit_competency	 math_A	 math_A_avg	 math_A_perc	 math_A_pop	 math_competency
math_gcse	 math_gcse_avg	 math_gcse_perc	 math_gcse_pop	 no_classes	 no_fail	 no_hs_student	 no_hs_student_female	 no_rooms
parttime_teachers	 pd	 requests	 res	 school_address	 school_dean	 school_dean_title	 school_id	 school_name
school_type	 soup	 t_2017	 t_2018	 t_2019	 t_2020	 t_basics	 t_enroll2019	 t_iq
t_students	 t_teachers	 test_table	 total_teachers

In [338]:
cols = ['school_id',
'school_name ',
'school_dean' ,
'school_dean_title',
'school_address',
'school_type',
'no_hs_student',
'no_hs_student_female' ,
'no_rooms ',
'no_classes',
'no_fail', 
'fulltime_teachers',
'parttime_teachers',
'total_teachers',
'first_place_acceptance_rate', 
'acceptance_rate',
'hu_gcse_pop','hu_gcse_perc','hu_gcse_avg',
'hu_A_pop','hu_A_perc','hu_A_avg',
'math_gcse_pop','math_gcse_perc','math_gcse_avg',
'math_A_pop','math_A_perc','math_A_avg', 
'hist_gcse_pop','hist_gcse_perc','hist_gcse_avg',
'hist_A_pop','hist_A_perc','hist_A_avg',
'eng_gcse_pop','eng_gcse_perc','eng_gcse_avg',
'eng_A_pop','eng_A_perc','eng_A_avg',
'math_competency','lit_competency']

In [341]:
pd.DataFrame(data=[school_id,
                    school_name ,
                    school_dean ,
                    school_dean_title,
                    school_address,
                    school_type,
                    no_hs_student,
                    no_hs_student_female ,
                    no_rooms ,
                    no_classes,
                    no_fail, 
                    fulltime_teachers,
                    parttime_teachers,
                    total_teachers,
                    first_place_acceptance_rate, 
                    acceptance_rate,
                    hu_gcse_pop,hu_gcse_perc,hu_gcse_avg,
                    hu_A_pop,hu_A_perc,hu_A_avg,
                    math_gcse_pop,math_gcse_perc,math_gcse_avg,
                    math_A_pop,math_A_perc,math_A_avg, 
                    hist_gcse_pop,hist_gcse_perc,hist_gcse_avg,
                    hist_A_pop,hist_A_perc,hist_A_avg,
                    eng_gcse_pop,eng_gcse_perc,eng_gcse_avg,
                    eng_A_pop,eng_A_perc,eng_A_avg,
                    math_competency,lit_competency
                    ],index=cols).T

,school_id,school_name,school_dean,school_dean_title,school_address,school_type,no_hs_student,no_hs_student_female,no_rooms,no_classes,...,hist_gcse_avg,hist_A_pop,hist_A_perc,hist_A_avg,eng_gcse_pop,eng_gcse_perc,eng_gcse_avg,eng_A_pop,eng_A_perc,eng_A_avg
0,035219,Budapest I. Kerületi Szilágyi Erzsébet Gimnázium,Bajkó Judit,intézményvezető,"1016 Budapest I. kerület, Mészáros utca 5-7.",[8 évfolyamos gimnáziumi nevelés-oktatás],501,256,21,16,...,4.65,8,73 %,4.88,19,88 %,4.89,25,77 %,4.76